name: Run Smoke Tests
description: Executes Smoke Tests
inputs:
  role-to-assume:
    description: an IAM role to use in tests
    required: true
  region:
    description: an AWS region to run in
    required: false
    default: us-west-2
runs:
  using: 'composite'
  steps:
    - name: Verify Amplify Path
      shell: bash
      run: |
        if [[ -z "$AMPLIFY_PATH" ]]; then
          echo "AMPLIFY_PATH must be defined"
          exit 1
        fi
        echo "AMPLIFY_PATH=$AMPLIFY_PATH"
        $AMPLIFY_PATH version

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.region }}

    - name: Install AWS CLI
      shell: powershell
      run: |
        msiexec.exe /i https://awscli.amazonaws.com/AWSCLIV2.msi /qn
        aws --version

    - name: Run Smoke Tests
      shell: bash
      run: .github/actions/run-smoke-tests-windows/windows-smoke-tests.sh

    - name: Cleanup
      shell: bash
      if: always()
      run: |
        cd $AMPLIFY_PROJ_DIR
        cd ..
        rm -rf $AMPLIFY_PROJ_DIR
