
version: 2.1

jobs:
  run-e2e_resource_cleanup:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Run scheduled workflow
          command: |
            curl --location --request POST 'https://circleci.com/api/v2/project/gh/aws-amplify/amplify-cli/pipeline' \
            --header 'Content-Type: application/json' \
            -u "${CCI_CONTINUATION_TOKEN}:" \
            --data-raw '{
              "branch": "dev",
                "parameters": {
                  "setup": false,
                  "nightly_console_integration_tests": false,
                  "e2e_resource_cleanup": true
              }
            }'
workflows:
  trigger_e2e_resource_cleanup:
    triggers:
      - schedule:
          cron: 45 0,12 * * *
          filters:
            branches:
              only:
                - nightly-jobs
    jobs:
      - run-e2e_resource_cleanup
  run_on_push:
    jobs:
      - run-e2e_resource_cleanup:
          filters:
            branches:
              only: nightly-jobs

