version: 0.2
env:
  shell: bash
  variables:
    E2E_TEST_COVERAGE_DIR: node_v8_coverage
    CI: true
    CIRCLECI: true
phases:
  build:
    commands:
      - source ./shared-scripts.sh && _amplifyGeneralConfigTests
  post_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - source ./shared-scripts.sh && _uploadReportsToS3 $CODEBUILD_SOURCE_VERSION $CODEBUILD_BATCH_BUILD_IDENTIFIER amplify-e2e-tests
reports:
  e2e-reports:
    files:
      - '*.xml'
    file-format: 'JUNITXML'
    base-directory: '$CODEBUILD_SRC_DIR/packages/amplify-e2e-tests/reports/junit'
