name: Run Smoke Tests

on:
  push:
    branches: [smoke-tests-prototype]

env:
  NODE_OPTIONS: --max-old-space-size=8096

jobs:
  run-smoke-tests:
    runs-on: macos-latest-xl
    steps:
      - name: Checkout Code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          persist-credentials: false

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build-tests

      - name: Install CLI
        run: |
          npm install -g @aws-amplify/cli@rc
          AMPLIFY_PATH=$(which amplify)
          echo "AMPLIFY_PATH=$AMPLIFY_PATH"
          echo "AMPLIFY_PATH=$AMPLIFY_PATH" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.SMOKE_TESTS_ROLE_ARN }}
          aws-region: us-west-2

      - name: Run Smoke Tests
        run: yarn smoketest

      - name: Upload Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test report
          path: packages/amplify-e2e-tests/amplify-e2e-reports
