name: Smoke Tests - Manual Run

# This is required by aws-actions/configure-aws-credentials
permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [smoke-tests-prototype]

jobs:
  call-smoke-tests:
    uses: ./.github/workflows/smoke-tests.yml
